site_name: Medialabbet – Introduktionskurs i generativ AI
site_url: https://fvk-medialabbet.github.io/ai-kurs-medialabbet/

repo_name: FVK-Medialabbet / AI-kurs
repo_url: https://github.com/FVK-Medialabbet/ai-kurs-medialabbet

theme:
  name: material
  language: sv
  logo: assets/images/medialabbet-logo-icon.svg
  favicon: assets/images/medialabbet-logo-icon.svg
  palette:
    - scheme: default          # Ljust läge
      primary: "light green"   # Huvudfärg (topbar m.m.)
      accent: "light green"    # Accentfärg (knappar, länkar m.m.)
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - search.highlight
    - search.suggest

nav:
  - Start: index.md
  - Referenser och licens: referenser.md
  - Videoresurser: videoresurser.md
  - Videobank: videobank.md
  - Chatt-server: zulip-kurs-chatt.md
  - Kursmaterial:
      - ChatGPT – grunder: chatgpt-grunder.md
      - Prompt engineering – nivå 1: prompt-engineering-niva-1.md
  - Ordlista: ordlista.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
